### ISSUE TITLE
Add Thunderbird 68 compatibility

### ISSUE THREAD

**Issue by tooomm** [micz/LightningColorReminders#11]

**Comment by jameshibbard** [comment]
@tooomm: I will submit an updated version of the addon to the TB addons site today. If you have any problems with it, I'd appreciate you letting me know.

**Comment by tooomm** [comment]
There is still no update available for me...

**Comment by jameshibbard** [comment]
Yeah, sorry about that. I submitted the updated version to the addons platform 21 days ago and it is still waiting to be approved.

In the meantime, I published a new release which you can install manually.
https://github.com/micz/LightningColorReminders/releases/tag/1.3

Sorry about the wait...
